[package]
name = "packing_codegen"
version = "0.1.0"
authors = ["cs2dsb <cs2dsb@gmail.com>"]
edition = "2018"

[dependencies]
syn = { version = "1.0.14", features = [ "extra-traits" ] }
quote = "1.0.2"
proc-macro2 = "1.0.8"

[lib]
proc-macro = true

[features]
diagnostic-notes = []
